<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
class Product extends Model implements HasMedia
{

    use HasMediaTrait;

    protected  $guarded = [];



    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static ::creating(function ($category){

            $category->slug = Str::slug($category->title);
        });
    }

    public  function  category(){  //product has a category
        return $this->hasOne(Category::class);
    }
}
